package com.acoding.hospital.ui.theme

import androidx.compose.ui.graphics.Color

val greenBackground = Color(0xFF119B00)

val primaryLight = Color(0xFF38693C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB9F0B7)
val onPrimaryContainerLight = Color(0xFF002106)
val secondaryLight = Color(0xFF526350)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD4E8D0)
val onSecondaryContainerLight = Color(0xFF101F10)
val tertiaryLight = Color(0xFF39656B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCEBF2)
val onTertiaryContainerLight = Color(0xFF001F23)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7FBF2)
val onBackgroundLight = Color(0xFF181D18)
val surfaceLight = Color(0xFFF7FBF2)
val onSurfaceLight = Color(0xFF181D18)
val surfaceVariantLight = Color(0xFFDEE5D9)
val onSurfaceVariantLight = Color(0xFF424940)
val outlineLight = Color(0xFF72796F)
val outlineVariantLight = Color(0xFFC2C9BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D322C)
val inverseOnSurfaceLight = Color(0xFFEEF2E9)
val inversePrimaryLight = Color(0xFF9ED49D)
val surfaceDimLight = Color(0xFFD7DBD3)
val surfaceBrightLight = Color(0xFFF7FBF2)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F5EC)
val surfaceContainerLight = Color(0xFFEBEFE6)
val surfaceContainerHighLight = Color(0xFFE6E9E1)
val surfaceContainerHighestLight = Color(0xFFE0E4DB)