package com.acoding.hospital.ui.theme

import androidx.compose.ui.graphics.Color

val greenBackground = Color(0xFF119B00)

val LightGray = Color(0xFFE0E0E0)
val Gray = Color(0xFF9E9E9E)
val DarkGray = Color(0xFF757575)
val White50 = Color(0xFFF5F5F5)

val primaryLight = Color(0xFF247CFF)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF006FF0)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF435D94)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB3C9FF)
val onSecondaryContainerLight = Color(0xFF19366B)
val tertiaryLight = Color(0xFF811CA1)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAA4AC9)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF181B23)
val surfaceLight = Color(0xFFFAF9FF)
val onSurfaceLight = Color(0xFF181B23)
val surfaceVariantLight = Color(0xFFDEE2F3)
val onSurfaceVariantLight = Color(0xFF414754)
val outlineLight = Color(0xFF727786)
val outlineVariantLight = Color(0xFFC1C6D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3039)
val inverseOnSurfaceLight = Color(0xFFEFF0FB)
val inversePrimaryLight = Color(0xFFAEC6FF)
val surfaceDimLight = Color(0xFFD8D9E4)
val surfaceBrightLight = Color(0xFFFAF9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3FE)
val surfaceContainerLight = Color(0xFFECEDF8)
val surfaceContainerHighLight = Color(0xFFE6E7F3)
val surfaceContainerHighestLight = Color(0xFFE0E2ED)